### ISSUE TITLE
Is it comfortable? :)

### ISSUE THREAD

**Issue by svbackend** [tarlepp/links-of-the-week#1]
Hello, I mean to just post links you can use some more adapted services for that (or write new one for yourself). It should be like google docs (easy to add some new links) + ability for other people to subscribe for changes, because commit & push every new link it a little bit boring, isn't it? + In email notifications from github about changes I don't receive links that you posted, only commit message, and I'm too lazy to open github commit page and look for green-lighted new link, so, is there any chances to use another platform for this links?

**Comment by tarlepp** [comment]
this is just for my personal usage - I like to use github for basically anything - and you won't get any messages from this repository if you just unsubcribe from it.

**Comment by svbackend** [comment]
I do want to get notifications about links, but just noted that github is probably not the best place to store them due some limits (described in 1st message), but if you don't want to change anything - it's fine, just saying, nothing more)

**Comment by tarlepp** [comment]
Hmm, it's _your_ decision if you want to get notifications from this repo or not - I cannot decide that.

**Comment by svbackend** [comment]
I think we just don't understand each other, 
I subscribed because I'm interested in this repo and of course it's my decision, BUT in this issue I just wanted to ask your thoughts about some alternatives, if you're good with github - cool, but if you think(or care) about subscribers - then maybe it would be better to use something more adapted for that? And of cource if you posting only for yourself and you're fine with github - it's fine, then I have no other suggestions/ideas, bye :)

**Comment by svbackend** [comment]
Actually this issue just to suggest some ideas, as suggested in one of your bookmarked atricles: https://medium.com/@decathlonDevelopers/open-source-mindset-benefits-5245f38957f4 ("Mindset benefits" part)
Peace)

**Comment by tarlepp** [comment]
oh, sorry I you get hostile vibe on my comments on this issue - that was not the purpose at all, and really sorry if that was the case.

**Comment by svbackend** [comment]
No no, all is fine, thanks for the replies
